In [12]:
from bats_label_model import BatsModel
import numpy as np
import pickle

In [3]:
model = BatsModel("MTurkSF")

100%|██████████| 100/100 [00:00<00:00, 470.29epoch/s]
/workspace/pruning_lfs.py:52: RuntimeWarning: invalid value encountered in scalar divide
  merged_data.append([index, polarity, cov_simp, cov_src, precision, 1 - precision, cov_simp+cov_src, abs(cov_simp - cov_src), abs(cov_simp - cov_src)/(cov_simp+cov_src)])


In [4]:
weights = model.label_model.get_weights()

/usr/local/lib/python3.8/site-packages/snorkel/labeling/model/label_model.py:387: RuntimeWarning: divide by zero encountered in divide
  return np.clip(accs / self.coverage, 1e-6, 1.0)


In [5]:
len(weights)

328

In [6]:
np.sum(weights)

271.41527601890243

In [7]:
weights

array([0.96194698, 0.94821669, 0.95290867, 0.94552225, 0.93662483,
       0.93108797, 0.90712456, 0.90388951, 0.88531515, 0.84030419,
       0.76680431, 0.85770602, 0.90444662, 0.93324914, 0.98498478,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.36036263, 1.        ,
       1.        , 1.        , 1.        , 0.9917048 , 1.        ,
       0.59083402, 1.        , 1.        , 1.        , 0.62489727,
       1.        , 1.        , 1.        , 1.        , 0.9539656 ,
       0.91701342, 1.        , 1.        , 1.        , 0.9345297 ,
       0.95360773, 0.94669524, 0.94613218, 0.78217966, 0.74080209,
       0.45792033, 0.48611527, 0.51263496, 0.65157626, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.99296066, 1.        , 0.94520915, 0.71858

In [8]:
norm_weigts = weights/np.sum(weights)

In [9]:
np.sum(norm_weigts)

0.9999999999999999

In [10]:
all_lfs = model.all_lfs

In [ ]:
with open("/workspace/datasets/eval_simp_labels.pkl", 'rb') as f:
    eval_simp = pickle.load(f)

NameError: name 'pickle' is not defined

In [14]:
with open("workspace/datasets/final_combined_with_index.pkl", 'rb') as f:
    dataset = pickle.load(f)

In [15]:
dataset['simplified_snt'] = dataset['simp']
dataset['source_snt'] = dataset['src']

In [16]:
selected_dataset = "MTurkSF"
dataset = dataset[dataset['ds_id'] == selected_dataset]

In [37]:
dataset

ds_id  Year Target_Audience   Domain             index  \
506530  MTurkSF  2022     non-experts  medical     MTurkSF__0__0   
506531  MTurkSF  2022     non-experts  medical     MTurkSF__0__1   
506532  MTurkSF  2022     non-experts  medical     MTurkSF__0__2   
506533  MTurkSF  2022     non-experts  medical     MTurkSF__0__3   
506534  MTurkSF  2022     non-experts  medical     MTurkSF__0__4   
...         ...   ...             ...      ...               ...   
506746  MTurkSF  2022     non-experts  medical  MTurkSF__62__216   
506747  MTurkSF  2022     non-experts  medical  MTurkSF__62__217   
506748  MTurkSF  2022     non-experts  medical  MTurkSF__60__218   
506749  MTurkSF  2022     non-experts  medical  MTurkSF__60__219   
506750  MTurkSF  2022     non-experts  medical  MTurkSF__60__220   

                                                      src  src_id  \
506530  Abdominal wall defects are a type of congenita...       0   
506531  Abdominal wall defects are a type of congenita...       0   
506532  Abdominal wall defects are a type of congenita...       0   
506533  Abdominal wall defects are a type of congenita...       0   
506534  Abdominal wall defects are a type of congenita...       0   
...                                                   ...     ...   
506746  Visual impairment may cause difficulties with ...      62   
506747  Visual impairment may cause difficulties with ...      62   
506748  Visual impairment, also known as vision impair...      60   
506749  Visual impairment, also known as vision impair...      60   
506750  Visual impairment, also known as vision impair...      60   

                                                     simp  simp_id label  ...  \
506530  Abdominal wall defects are a type of congenita...        0   NaN  ...   
506531  Abdominal wall defects are a type of congenita...        1   NaN  ...   
506532  Abdominal wall defects are a type of congenita...        2   NaN  ...   
506533  Abdominal wall defects are a type of congenita...        3   NaN  ...   
506534  Abdominal wall defects are a type of congenita...        4   NaN  ...   
...                                                   ...      ...   ...  ...   
506746  Visual impairment may cause difficult with nor...      216   NaN  ...   
506747  Visual impairment may cause trouble with norma...      217   NaN  ...   
506748  Visual impairment, also known as vision impair...      218   NaN  ...   
506749  Visual impairment, also known as vision impair...      219   NaN  ...   
506750  Visual impairment, also known as vision impair...      220   NaN  ...   

       granularity duplicated                topic src_title simp_title  \
506530    sentence      False  abdominalwalldefect       NaN        NaN   
506531    sentence      False  abdominalwalldefect       NaN        NaN   
506532    sentence      False  abdominalwalldefect       NaN        NaN   
506533    sentence      False  abdominalwalldefect       NaN        NaN   
506534    sentence      False  abdominalwalldefect       NaN        NaN   
...            ...        ...                  ...       ...        ...   
506746    sentence      False    visual-impairment       NaN        NaN   
506747    sentence      False    visual-impairment       NaN        NaN   
506748    sentence      False    visual-impairment       NaN        NaN   
506749    sentence      False    visual-impairment       NaN        NaN   
506750    sentence      False    visual-impairment       NaN        NaN   

       similarity  topics val_split  \
506530        NaN     NaN     False   
506531        NaN     NaN     False   
506532        NaN     NaN     False   
506533        NaN     NaN     False   
506534        NaN     NaN     False   
...           ...     ...       ...   
506746        NaN     NaN     False   
506747        NaN     NaN     False   
506748        NaN     NaN     False   
506749        NaN     NaN     False   
506750        NaN     NaN     False   

                     

In [47]:
for i in range(30):
    t1 = dataset.iloc[1].simp
    print(model.calc_score(t1))

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


1.0

In [23]:
t1_bin =model.transform_to_bin_vec(t1)

In [35]:
t1_bin

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1, -1,  0, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1,  1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  0,
        -1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1, -1, -1, -1,
        -1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,
         1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         1,  1, -1, -1, -1, -1, -1,  0,  0, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
         1,  1,  1,  1,  1,  1,  1,  0,  0, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 

In [27]:
weights

array([0.96194698, 0.94821669, 0.95290867, 0.94552225, 0.93662483,
       0.93108797, 0.90712456, 0.90388951, 0.88531515, 0.84030419,
       0.76680431, 0.85770602, 0.90444662, 0.93324914, 0.98498478,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.36036263, 1.        ,
       1.        , 1.        , 1.        , 0.9917048 , 1.        ,
       0.59083402, 1.        , 1.        , 1.        , 0.62489727,
       1.        , 1.        , 1.        , 1.        , 0.9539656 ,
       0.91701342, 1.        , 1.        , 1.        , 0.9345297 ,
       0.95360773, 0.94669524, 0.94613218, 0.78217966, 0.74080209,
       0.45792033, 0.48611527, 0.51263496, 0.65157626, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.99296066, 1.        , 0.94520915, 0.71858

In [32]:
s_val = 0
ns_val = 0

for i in range(len(t1_bin[0])):
    if t1_bin[0][i] == 0:
        s_val += weights[i]
    elif t1_bin[0][i] == 1:
        ns_val += weights[i]

In [33]:
s_val

24.42302832058494

In [34]:
ns_val

39.62999288092415

In [36]:
t1_bin[0]

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1,  0, -1, -1, -1,  0, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,  1,  1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  0, -1, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0, -1, -1, -1, -1, -1, -1, -1,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1,  0,  0, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1,  0